
USE imporfrut19_21;

CREATE TABLE CLIENTE (
ID_CLIENTE int primary key not null,
NOMBRE nvarchar,
TELEFONO int,
EMAIL nvarchar(200),
TIPO_FACTURACION nvarchar(200),
ID_PLAZA int
);
CREATE TABLE PLAZA (
ID_PLAZA int primary key not null,
ID_CLIENTE int,
ID_VENDEDOR int
);
CREATE TABLE VENDEDOR (
ID_VENDEDOR int primary key not null,
NOMBRE nvarchar(200), 
ID_PLAZA int 
);

ALTER TABLE CLIENTE 
	ADD FOREIGN KEY (ID_PLAZA) references PLAZA (ID_PLAZA)

ALTER TABLE VENDEDOR
	ADD FOREIGN KEY (ID_PLAZA) references PLAZA (ID_PLAZA)

ALTER TABLE PLAZA 
	ADD FOREIGN KEY (ID_CLIENTE) references CLIENTE (ID_CLIENTE)
ALTER TABLE PLAZA
	ADD FOREIGN KEY (ID_VENDEDOR) references VENDEDOR (ID_VENDEDOR)